import Footer from "./(components)/Footer";
import Nav from "./(components)/Navbar";
import "./globals.css";
import Providers from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Providers>
          <Nav />
          <div className="md:px-14 px-2 py-8">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
